apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eraser-leader-election-role
  namespace: '{{ .Release.Namespace }}'
  labels:
    app: '{{ template "eraser.name" . }}'
    chart: '{{ template "eraser.name" . }}'
    eraser.sh/system: "yes"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch