apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eraser-leader-election-rolebinding
  labels:
    {{- include "eraser.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eraser-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "eraser.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
