# permissions for end users to edit imagelists.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagelist-editor-role
rules:
- apiGroups:
  - batch.k8s.io
  resources:
  - imagelists
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.k8s.io
  resources:
  - imagelists/status
  verbs:
  - get
