# permissions for end users to view imagelists.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagelist-viewer-role
rules:
- apiGroups:
  - batch.k8s.io
  resources:
  - imagelists
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.k8s.io
  resources:
  - imagelists/status
  verbs:
  - get
