apiVersion: v1
kind: Namespace
metadata:
  name: eraser-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eraser
  namespace: eraser-system
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - eraser.sh
  resources:
  - imagejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eraser.sh
  resources:
  - imagejobs/finalizers
  verbs:
  - update
- apiGroups:
  - eraser.sh
  resources:
  - imagejobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - eraser.sh
  resources:
  - imagelists
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eraser.sh
  resources:
  - imagelists/finalizers
  verbs:
  - update
- apiGroups:
  - eraser.sh
  resources:
  - imagelists/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - eraser.sh
  resources:
  - imagestatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eraser.sh
  resources:
  - imagestatuses/finalizers
  verbs:
  - update
- apiGroups:
  - eraser.sh
  resources:
  - imagestatuses/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eraser
  namespace: eraser-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eraser
subjects:
  - kind: ServiceAccount
    name: eraser-controller-manager
    namespace: eraser-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eraser-controller-manager
  namespace: eraser-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: eraser-manager
  name: eraser-manager
  namespace: eraser-system
spec:
  selector:
    matchLabels:
      component: eraser-manager
  replicas: 1
  template:
    metadata:
      labels:
        component: eraser-manager
    spec:
      serviceAccountName: eraser-controller-manager
      containers:
      - command:
        - /manager
        image: ghcr.io/azure/eraser-manager:v0.1.0
        imagePullPolicy: IfNotPresent
        name: eraser-manager
