apiVersion: eraser.sh/v1alpha1
kind: ImageJob
metadata:
  name: imagejob-sample
spec:
  template:
    spec:
      containers:
      - name: eraser
        image: ashnam/remove-images
      restartPolicy: OnFailure
