apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: '{{ template "eraser.name" . }}'
    chart: '{{ template "eraser.name" . }}'
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: eraser-controller-manager
  namespace: '{{ .Release.Namespace }}'
